### ISSUE TITLE
New parser: repquota

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#222]
Thanks for this awesome tool!

The Debian quota package [provides the `repquota` tool](https://packages.debian.org/search?searchon=contents&keywords=repquota&mode=path&suite=stable&arch=any), this [supports CSV and XML output](https://manpages.debian.org/bullseye/quota/repquota.8.en.html) and I have been having a play with converting the XML into JSON for Ansible local facts using `xsltproc` with a [XSLT transformation to make all the attributes elements](https://stackoverflow.com/a/10645490) and `xq`, for example `repquota /home -O xml` outputs:

```xml
<?xml version="1.0"?>
<repquota>
<Report type='user' dev='/dev/xvda4'>
 <BlockGraceTime>24:00</BlockGraceTime>
 <InodeGraceTime>24:00</InodeGraceTime>
 <Quota user='root'>
  <QuotaStatus block='ok' inode='ok' />
  <blockLimits used='188' soft='0' hard='0' grace='' />
  <FileLimits used='45' soft='0' hard='0' grace='' />
 </Quota>
 <Quota user='chris'>
  <QuotaStatus block='ok' inode='ok' />
  <blockLimits used='22064' soft='0' hard='0' grace='' />
  <FileLimits used='455' soft='0' hard='0' grace='' />
 </Quota>
</Report>
</repquota>
```

And when the XSLT linked above is added, for example `repquota /home -O xml | xsltproc /etc/ansible/attributetoelement.xslt -` the XML looks like this:

```xml
<?xml version="1.0"?>
<repquota>
<Report><type>user</type><dev>/dev/xvda4</dev>
 <BlockGraceTime>24:00</BlockGraceTime>
 <InodeGraceTime>24:00</InodeGraceTime>
 <Quota><user>root</user>
  <QuotaStatus><block>ok</block><inode>ok</inode></QuotaStatus>
  <blockLimits><used>188</used><soft>0</soft><hard>0</hard><grace/></blockLimits>
  <FileLimits><used>45</used><soft>0</soft><hard>0</hard><grace/></FileLimits>
 </Quota>
 <Quota><user>chris</user>
  <QuotaStatus><block>ok</block><inode>ok</inode></QuotaStatus>
  <blockLimits><used>22064</used><soft>0</soft><hard>0</hard><grace/></blockLimits>
  <FileLimits><used>455</used><soft>0</soft><hard>0</hard><grace/></FileLimits>
 </Quota>
</Report>
</repquota>
```

Then using `xq` to convert it into JSON and remove the redundant top level elements `repquota /home -O xml | xsltproc /etc/ansible/attributetoelement.xslt - | xq -M '.repquota.Report'` results in:

```json
{
  "type": "user",
  "dev": "/dev/xvda4",
  "BlockGraceTime": "24:00",
  "InodeGraceTime": "24:00",
  "Quota": [
    {
      "user": "root",
      "QuotaStatus": {
        "block": "ok",
        "inode": "ok"
      },
      "blockLimits": {
        "used": "188",
        "soft": "0",
        "hard": "0",
        "grace": null
      },
      "FileLimits": {
        "used": "45",
        "soft": "0",
        "hard": "0",
        "grace": null
      }
    },
    {
      "user": "chris",
      "QuotaStatus": {
        "block": "ok",
        "inode": "ok"
      },
      "blockLimits": {
        "used": "22064",
        "soft": "0",
        "hard": "0",
        "grace": null
      },
      "FileLimits": {
        "used": "455",
        "soft": "0",
        "hard": "0",
        "grace": null
      }
    }
  ]
}
```

And if this command is saved as `/etc/ansible/facts.d/repquota.fact` and made executable the following YAML is returned when Ansible gathers facts:

```yaml
ansible_facts:
    ansible_local:
        repquota:
            BlockGraceTime: '24:00'
            InodeGraceTime: '24:00'
            Quota:
            -   FileLimits:
                    grace: null
                    hard: '0'
                    soft: '0'
                    used: '45'
                QuotaStatus:
                    block: ok
                    inode: ok
                blockLimits:
                    grace: null
                    hard: '0'
                    soft: '0'
                    used: '188'
                user: root
            -   FileLimits:
                    grace: null
                    hard: '0'
                    soft: '0'
                    used: '457'
                QuotaStatus:
                    block: ok
                    inode: ok
                blockLimits:
                    grace: null
                    hard: '0'
                    soft: '0'
                    used: '22068'
                user: chris
```
Perhaps `repquota` would be a suitable candidate for a `jc` parser?
