### ISSUE TITLE
New parser: gpg

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#257]
The `gpg` command has a [machine readable output format](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob_plain;f=doc/DETAILS), see [this Stackoverflow comment](https://stackoverflow.com/a/22147722/9669328) and [the one after it](), for example (you can also add `-vv` for a more verbose output):

```bash
gpg --with-colons --show-keys /usr/share/keyrings/debian-archive-bullseye-stable.gpg 
pub:-:4096:1:605C66F00D6C9793:1613238862:1865526862::-:::scSC::::::23::0:
fpr:::::::::A4285295FC7B1A81600062A9605C66F00D6C9793:
uid:-::::1613238862::2C045EB517DDC06A1FC747D1E310AD33A8CB50E4::Debian Stable Release Key (11/bullseye) <debian-release@lists.debian.org>::::::::::0:
```

The above command can currently be used via Ansible to check keys, for example for Docker:

```yml
- name: Set a variable for the Docker GPG fingerprint 
  ansible.builtin.set_fact:
    docker_gpg_fingerprint: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Docker GPG key present
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644
    owner: root
    group: root

- name: Docker GPG key check command
  ansible.builtin.command: gpg --with-colons --show-keys -v /etc/apt/keyrings/docker.asc
  check_mode: false
  changed_when: false
  register: docker_gpg

- name: Docker GPG key checked
  ansible.builtin.assert:
    that:
      - docker_gpg_fingerprint in docker_gpg.stdout
```

Which is fine, but it could be nicer -- would this be a suitable command to consider for a `jc` parser?

**Comment by kellyjonbrazil** [comment]
Cool - I'll take a look at this. Looks like a good candidate for a parser. Thanks!

**Comment by chriscroome** [comment]
Note that with older versions of `gpg` the command needs to be:

```bash
gpg --with-colons --with-fingerprint --with-subkey-fingerprint /etc/apt/keyrings/docker.asc
```

**Comment by kellyjonbrazil** [comment]
Thanks for the documentation links. I've begun work on this and it doesn't seem like it will be too difficult. I'll start out simply pulling the 21 defined fields into keys. I'll play with it a bit after that to see if there is any more processing that makes sense, like additional keys that map codes to nicer name strings and such.

**Comment by chriscroome** [comment]
I installed it:

```bash
mkdir ~/.local/share/jc/jcparsers
wget https://raw.githubusercontent.com/kellyjonbrazil/jc/dev/jc/parsers/gpg.py -O ~/.local/share/jc/jcparsers/gpg.py
```

And tested it:

```bash
jc gpg --with-colons --show-keys /usr/share/keyrings/debian-archive-bullseye-stable.gpg
```

And this results in:

```json
[
  {
    "type": "pub",
    "validity": "-",
    "key_length": "4096",
    "pub_key_alg": "1",
    "key_id": "605C66F00D6C9793",
    "creation_date": "1613238862",
    "expiration_date": "1865526862",
    "certsn_uidhash_trustinfo": null,
    "owner_trust": "-",
    "user_id": null,
    "signature_class": null,
    "key_capabilities": "scSC",
    "cert_fingerprint_other": null,
    "flag": null,
    "token_sn": null,
    "hash_alg": null,
    "curve_name": null,
    "compliance_flags": "23",
    "last_update_date": null,
    "origin": "0",
    "comment": null
  },
  {
    "type": "fpr",
    "validity": null,
    "key_length": null,
    "pub_key_alg": null,
    "key_id": null,
    "creation_date": null,
    "expiration_date": null,
    "certsn_uidhash_trustinfo": null,
    "owner_trust": null,
    "user_id": "A4285295FC7B1A81600062A9605C66F00D6C9793",
    "signature_class": null,
    "key_capabilities": null,
    "cert_fingerprint_other": null,
    "flag": null,
    "token_sn": null,
    "hash_alg": null,
    "curve_name": null,
    "compliance_flags": null,
    "last_update_date": null,
    "origin": null,
    "comment": null
  },
  {
    "type": "uid",
    "validity": "-",
    "key_length": null,
    "pub_key_alg": null,
    "key_id": null,
    "creation_date": "1613238862",
    "expiration_date": null,
    "certsn_uidhash_trustinfo": "2C045EB517DDC06A1FC747D1E310AD33A8CB50E4",
    "owner_trust": null,
    "user_id": "Debian Stable Release Key (11/bullseye) <debian-release@lists.debian.org>",
    "signature_class": null,
    "key_capabilities": null,
    "cert_fingerprint_other": null,
    "flag": null,
    "token_sn": null,
    "hash_alg": null,
    "curve_name": null,
    "compliance_flags": null,
    "last_update_date": null,
    "origin": "0",
    "comment": null
  }
]
```

And it can be filtered using [jp](https://github.com/jmespath/jp), like this:

```bash
jc -p gpg --with-colons --show-keys /usr/share/keyrings/debian-archive-bullseye-stable.gpg | jp [].user_id
[
  "A4285295FC7B1A81600062A9605C66F00D6C9793",
  "Debian Stable Release Key (11/bullseye) \u003cdebian-release@lists.debian.org\u003e"
]
```

Looks ideal!

**Comment by kellyjonbrazil** [comment]
Cool - I'll work on it some more, but if you want this raw output in the production version, just use `jc -r`. I'm also looking into parsing `openssl` for certificates, and also just natively supporting PEM and DER, etc. formats like `cat cert.pem | jc --pem` or something like that.

**Comment by chriscroome** [comment]
The `openssl` parser sounds good, in the past I've [used Bash](https://git.coop/webarch/acmesh/-/blob/master/files/subject-alt-name-check.sh) to extract `subjectAltNames`... being able to parse the output of commands such as `openssl x509 -in cert.pem -text -noout` using `jc` would be handy, however I must admit that I'd probably use the [Ansible community.crypto.x509_certificate module](https://docs.ansible.com/ansible/latest/collections/community/crypto/x509_certificate_module.html) for things like these days.

I found a [OpenSSL issue to add JSON output](https://github.com/openssl/openssl/issues/7736) to the `openssl s_client` command, I don't know if that helps at all.

**Comment by kellyjonbrazil** [comment]
Available in v1.20.2

**Comment by chriscroome** [comment]
If at some point in the future you added GPG signatures (or a GPG signed text file with SHA256SUMS) for packages then we could use `jc` to check your key fingerprints and the packages prior to installing them :wink:

**Comment by kellyjonbrazil** [comment]
Cool - I have the SHA256SUMS but haven't published them since I didn't know a secure way. That makes sense - if I sign the file, then I can just add the SHA256SUMS file to the releases. I haven't really used GPG before. I'll look into it. Thanks again!

**Comment by chriscroome** [comment]
Fantastic, GPG does have a bit of a learning curve.

One example of this are [the Node.js binaries](https://nodejs.org/dist/latest-v16.x/), they have a signed version of the SHA265SUMS and a separate binary signature (some projects provide ASCII armored signatures), if you are automating everything then I guess you could provide binary and ASCII armored versions.

Another example is Firefox, they simply provide ASCII armored sigs for each archive file, see [the latest version](https://download-installer.cdn.mozilla.net/pub/firefox/releases/102.0.1/linux-x86_64/en-GB/) for an example.

**Comment by chriscroome** [comment]
For reference for anyone else using Ansible and JC to check GPG signatures this is the JMESPath query you need to use to get the fingerprints:

```yml
- name: Docker gpg key check command
  ansible.builtin.command: gpg --with-colons --show-keys /etc/apt/keyrings/docker.gpg
  register: docker_gpg

- name: Set a fact for the GPG fingerprints
  ansible.builtin.set_fact:
    docker_gpg_fingerprints: "{{ docker_gpg.stdout | community.general.jc('gpg') | community.general.json_query('[?type==`fpr`].user_id') | list }}"
```

The first fingerprint in the array is the one for the main key and any additional ones are from sub-keys.

See [the tasks here for a full example](https://git.coop/webarch/docker/-/blob/22e80b83704f3aa97a6d8c1a135a4d5c5a181c39/tasks/apt.yml).
