### ISSUE TITLE
Possible new parser: findmnt

### ISSUE THREAD

**Issue by MusicDev33** [kellyjonbrazil/jc#302]
It looks fairly straightforward; the output looks like this:

TARGET SOURCE FSTYPE OPTIONS
/home/me nfsmnt:/PEOPLE/me nfs rsize=65536,namlen=255

**Comment by chriscroome** [comment]
I'm not sure there is a need for this since `findmnt` has a JSON output option, use `findmnt -J`, [I discovered this yesterday](https://git.coop/-/snippets/100), for example:

```bash
findmnt -J /home | jq
```
Results in:

```json
{
  "filesystems": [
    {
      "target": "/home",
      "source": "/dev/xvda4",
      "fstype": "ext4",
      "options": "rw,nosuid,nodev,relatime,quota,usrquota"
    }
  ]
}
```

What is nice about it, compared with `cat /proc/mounts` or the `ansible_facts.mounts` data is the nesting and info about what exactly is mounted where, a more complicated example:

```bash
findmnt -J | yq -P
```

Results in the following YAML on a development server I run:

```yaml
filesystems:
  - target: /
    source: /dev/xvda2
    fstype: ext4
    options: rw,relatime,errors=remount-ro
    children:
      - target: /sys
        source: sysfs
        fstype: sysfs
        options: rw,nosuid,nodev,noexec,relatime
        children:
          - target: /sys/kernel/security
            source: securityfs
            fstype: securityfs
            options: rw,nosuid,nodev,noexec,relatime
          - target: /sys/fs/cgroup
            source: cgroup2
            fstype: cgroup2
            options: rw,nosuid,nodev,noexec,relatime,nsdelegate
          - target: /sys/fs/pstore
            source: pstore
            fstype: pstore
            options: rw,nosuid,nodev,noexec,relatime
          - target: /sys/fs/bpf
            source: bpf
            fstype: bpf
            options: rw,nosuid,nodev,noexec,relatime,mode=700
          - target: /sys/kernel/debug
            source: debugfs
            fstype: debugfs
            options: rw,nosuid,nodev,noexec,relatime
          - target: /sys/kernel/tracing
            source: tracefs
            fstype: tracefs
            options: rw,nosuid,nodev,noexec,relatime
          - target: /sys/kernel/config
            source: configfs
            fstype: configfs
            options: rw,nosuid,nodev,noexec,relatime
          - target: /sys/fs/fuse/connections
            source: fusectl
            fstype: fusectl
            options: rw,nosuid,nodev,noexec,relatime
      - target: /proc
        source: proc
        fstype: proc
        options: rw,relatime
        children:
          - target: /proc/sys/fs/binfmt_misc
            source: systemd-1
            fstype: autofs
            options: rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=10365
      - target: /dev
        source: udev
        fstype: devtmpfs
        options: rw,nosuid,relatime,size=4056296k,nr_inodes=1014074,mode=755
        children:
          - target: /dev/pts
            source: devpts
            fstype: devpts
            options: rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000
          - target: /dev/shm
            source: tmpfs
            fstype: tmpfs
            options: rw,nosuid,nodev
          - target: /dev/mqueue
            source: mqueue
            fstype: mqueue
            options: rw,nosuid,nodev,noexec,relatime
      - target: /run
        source: tmpfs
        fstype: tmpfs
        options: rw,nosuid,noexec,relatime,size=820348k,mode=755
        children:
          - target: /run/lock
            source: tmpfs
            fstype: tmpfs
            options: rw,nosuid,nodev,noexec,relatime,size=5120k
          - target: /run/user/1000
            source: tmpfs
            fstype: tmpfs
            options: rw,nosuid,nodev,relatime,size=820348k,nr_inodes=205087,mode=700,uid=1000,gid=1001
      - target: /var
        source: /dev/xvda3
        fstype: ext4
        options: rw,relatime,errors=remount-ro
        children:
          - target: /var/lib/mysql
            source: /dev/xvda6
            fstype: ext4
            options: rw,nosuid,nodev,relatime
          - target: /var/lib/snapd
            source: /dev/xvda7
            fstype: ext4
            options: rw,nosuid,nodev,relatime
          - target: /var/www/users/foobar
            source: /dev/xvda4[/foobar]
            fstype: ext4
            options: rw,nosuid,nodev,relatime,quota,usrquota
          - target: /var/www/users/stats
            source: /dev/xvda4[/stats]
            fstype: ext4
            options: rw,nosuid,nodev,relatime,quota,usrquota
      - target: /home
        source: /dev/xvda4
        fstype: ext4
        options: rw,nosuid,nodev,relatime,quota,usrquota
      - target: /chroot
        source: /dev/xvda5
        fstype: ext4
        options: rw,nosuid,relatime
      - target: /chroots/www-data
        source: /dev/xvda5
        fstype: ext4
        options: ro,nosuid,relatime
        children:
          - target: /chroots/www-data/run/mysqld
            source: tmpfs[/mysqld]
            fstype: tmpfs
            options: ro,nosuid,nodev,noexec,relatime,size=820348k,mode=755
          - target: /chroots/www-data/run/chroot
            source: tmpfs[/chroot]
            fstype: tmpfs
            options: ro,nosuid,nodev,noexec,relatime,size=820348k,mode=755
          - target: /chroots/www-data/run/php
            source: tmpfs[/php]
            fstype: tmpfs
            options: ro,nosuid,nodev,noexec,relatime,size=820348k,mode=755
          - target: /chroots/www-data/run/apache2
            source: tmpfs[/apache2]
            fstype: tmpfs
            options: ro,nosuid,nodev,noexec,relatime,size=820348k,mode=755
          - target: /chroots/www-data/usr/lib/apache2
            source: /dev/xvda2[/usr/lib/apache2]
            fstype: ext4
            options: ro,relatime,errors=remount-ro
          - target: /chroots/www-data/etc/apache2/suexec
            source: /dev/xvda2[/etc/apache2/suexec]
            fstype: ext4
            options: ro,nosuid,nodev,relatime,errors=remount-ro
          - target: /chroots/www-data/var/lib/apache2/fcgid/sock
            source: /dev/xvda3[/lib/apache2/fcgid/sock]
            fstype: ext4
            options: rw,nosuid,nodev,relatime,errors=remount-ro
          - target: /chroots/www-data/var/log/apache2
            source: /dev/xvda3[/log/apache2]
            fstype: ext4
            options: rw,nosuid,nodev,relatime,errors=remount-ro
          - target: /chroots/www-data/var/www/html
            source: /dev/xvda3[/www/html]
            fstype: ext4
            options: ro,nosuid,nodev,relatime,errors=remount-ro
          - target: /chroots/www-data/var/www/localhost
            source: /dev/xvda3[/www/localhost]
            fstype: ext4
            options: ro,nosuid,nodev,relatime,errors=remount-ro
          - target: /chroots/www-data/var/www/wsh
            source: /dev/xvda3[/www/wsh]
            fstype: ext4
            options: ro,nosuid,nodev,relatime,errors=remount-ro
          - target: /chroots/www-data/var/www/users/foobar
            source: /dev/xvda4[/foobar]
            fstype: ext4
            options: rw,nosuid,nodev,relatime,quota,usrquota
          - target: /chroots/www-data/var/www/users/stats
            source: /dev/xvda4[/stats]
            fstype: ext4
            options: rw,nosuid,nodev,relatime,quota,usrquota
      - target: /chroots/foobar
        source: /dev/xvda5
        fstype: ext4
        options: ro,nosuid,relatime
        children:
          - target: /chroots/foobar/run/chroot
            source: tmpfs[/chroot]
            fstype: tmpfs
            options: ro,nosuid,nodev,noexec,relatime,size=820348k,mode=755
          - target: /chroots/foobar/home/foobar
            source: /dev/xvda4[/foobar]
            fstype: ext4
            options: rw,nosuid,nodev,relatime,quota,usrquota
          - target: /chroots/foobar/run/mysqld
            source: tmpfs[/mysqld]
            fstype: tmpfs
            options: ro,nosuid,nodev,noexec,relatime,size=820348k,mode=755
          - target: /chroots/foobar/var/www/users/foobar
            source: /dev/xvda4[/foobar]
            fstype: ext4
            options: rw,nosuid,nodev,relatime,quota,usrquota
      - target: /chroots/stats
        source: /dev/xvda5
        fstype: ext4
        options: ro,nosuid,relatime
        children:
          - target: /chroots/stats/run/mysqld
            source: tmpfs[/mysqld]
            fstype: tmpfs
            options: ro,nosuid,nodev,noexec,relatime,size=820348k,mode=755
          - target: /chroots/stats/run/chroot
            source: tmpfs[/chroot]
            fstype: tmpfs
            options: ro,nosuid,nodev,noexec,relatime,size=820348k,mode=755
          - target: /chroots/stats/home/stats
            source: /dev/xvda4[/stats]
            fstype: ext4
            options: rw,nosuid,nodev,relatime,quota,usrquota
          - target: /chroots/stats/var/www/users/stats
            source: /dev/xvda4[/stats]
            fstype: ext4
            options: rw,nosuid,nodev,relatime,quota,usrquota
      - target: /snap/core/13886
        source: /dev/loop1
        fstype: squashfs
        options: ro,nodev,relatime
      - target: /snap/core/13741
        source: /dev/loop3
        fstype: squashfs
        options: ro,nodev,relatime
      - target: /snap/core18/2560
        source: /dev/loop0
        fstype: squashfs
        options: ro,nodev,relatime
      - target: /snap/core18/2566
        source: /dev/loop2
        fstype: squashfs
        options: ro,nodev,relatime
```
