### ISSUE TITLE
Possible new parser debconf-show 

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#303]
The [debconf-show](https://manpages.debian.org/bullseye/debconf/debconf-show.1.en.html) output can be parsed using the key/value parser after the `*` marking options that have been set have been removed, for example:

```bash
debconf-show onlyoffice-documentserver                                                
* onlyoffice/jwt-secret: aL8ei2iereuzee7cuJ6Cahjah1ixee2ah
* onlyoffice/db-pwd: (password omitted)
* onlyoffice/rabbitmq-pwd: (password omitted)
* onlyoffice/ds-port: 80
* onlyoffice/docservice-port: 8000
* onlyoffice/jwt-enabled: true
* onlyoffice/remove-db: false
* onlyoffice/jwt-header: Authorization
* onlyoffice/db-port: 5432
* onlyoffice/rabbitmq-user: onlyoffice
* onlyoffice/example-port: 3000
* onlyoffice/db-name: onlyoffice
* onlyoffice/db-host: localhost
* onlyoffice/db-type: postgres
* onlyoffice/rabbitmq-host: localhost
* onlyoffice/db-user: onlyoffice
* onlyoffice/rabbitmq-proto: amqp
* onlyoffice/cluster-mode: false

debconf-show onlyoffice-documentserver | sed 's/^[*]/ /' | sed 's/onlyoffice\///' | jc --kv -p
```

Results in:

```json
{
  "jwt-secret": "aL8ei2iereuzee7cuJ6Cahjah1ixee2ah",
  "db-pwd": "(password omitted)",
  "rabbitmq-pwd": "(password omitted)",
  "docservice-port": "8000",
  "db-port": "5432",
  "jwt-enabled": "true",
  "rabbitmq-host": "localhost",
  "ds-port": "80",
  "db-user": "onlyoffice",
  "db-type": "postgres",
  "remove-db": "false",
  "example-port": "3000",
  "rabbitmq-user": "onlyoffice",
  "db-name": "onlyoffice",
  "cluster-mode": "false",
  "rabbitmq-proto": "amqp",
  "jwt-header": "Authorization",
  "db-host": "localhost"
}
```

And then you can do things like conditionally set the values, for example using Ansible:

```yaml
    - name: Read the debconf for onlyoffice-documentserver
      ansible.builtin.shell: |
        set -e -o pipefail
        debconf-show onlyoffice-documentserver | sed 's/^[*]/ /' | sed 's/onlyoffice\///'
      args:
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: onlyoffice_debconf_show

    - name: Set a fact for the debconf for onlyoffice-documentserver
      ansible.builtin.set_fact:
        onlyoffice_debconf: "{{ onlyoffice_debconf_show.stdout | community.general.jc('kv') }}"

    - name: Debconf cluster-mode
      ansible.builtin.debconf:
        name: onlyoffice
        question: onlyoffice/cluster-mode
        value: "{{ onlyoffice_cluster_mode }}"
        vtype: boolean
      when: onlyoffice_debconf['cluster-mode'] | bool != onlyoffice_cluster_mode | bool

    - name: Debconf db-port
      ansible.builtin.debconf:
        name: onlyoffice
        question: onlyoffice/db-port
        value: "{{ onlyoffice_db_port }}"
        vtype: text
      when: onlyoffice_debconf['db-port'] | int != onlyoffice_db_port | int
```

However you have to set the variable types as everything is returned as strings, would it be worth considering a JC parser for `debconf-show`?

It could potentially set strings to booleans and integers also also perhaps show the questions that have already been asked (the `*`), perhaps something like this?

```yaml
debconf-show:
  onlyoffice:
    - name: jwt-secret
      value: "aL8ei2iereuzee7cuJ6Cahjah1ixee2ah"
      asked: true
    - name: ds-port
      value: 80
      asked: true
```
