### ISSUE TITLE
New parser: PostgreSQL Password File

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#326]
Being able to read the [PostgreSQL Password File](https://www.postgresql.org/docs/15/libpq-pgpass.html) as JSON would be handy and it is a very simple format:

> The file .pgpass in a user's home directory&hellip; should contain lines of the following format:
>
> ```
> hostname:port:database:username:password
> ```
>
> Each of the first four fields can be a literal value, or *, which matches anything. The password field from the first line that matches the current connection parameters will be used. (Therefore, put more-specific entries first when you are using wildcards.) If an entry needs to contain : or \, escape this character with \.

So `cat /var/lib/postgresql/.pgpass | jc -yp --pgpass` could perhaps return something like:

```yaml
---
- hostname: localhost
  port: 5432
  database: foo
  username: bar
  password: baz
```
