### ISSUE TITLE
Possible new parser: needrestart -b

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#339]
The [needrestart](https://manpages.debian.org/bullseye/needrestart/needrestart.1.en.html) command might be a fairly easy one to support using `-b` for [batch mode](https://github.com/liske/needrestart/blob/master/README.batch.md):

```bash
needrestart -b
```

Returns output like this:

```yaml
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 5.10.0-19-amd64
NEEDRESTART-KEXP: 5.10.0-20-amd64
NEEDRESTART-KSTA: 3
NEEDRESTART-SVC: exim4.service
NEEDRESTART-SVC: php7.4-fpm.service
```

Which is fine for the kernel output when parser using the INI parser:

```bash
needrestart -b | jc --ini -y
```

```yaml
---
NEEDRESTART-VER: '3.5'
NEEDRESTART-KCUR: 5.10.0-19-amd64
NEEDRESTART-KEXP: 5.10.0-20-amd64
NEEDRESTART-KSTA: '3'
NEEDRESTART-SVC: php7.4-fpm.service
```

However only the last service that needs restarting is listed, it would be nice if the `NEEDRESTART-SVC` variables were returned as a list, also perhaps the uppercase and dash results could be returned when using `--raw` and lowerecase variables, could be returned without, also perhaps `NEEDRESTART-KSTA` should be an `int`, for example:

```yaml
ver: '3.5'
kcur: 5.10.0-19-amd64
kexp: 5.10.0-20-amd64
ksta: 3
svc:
  - exim4.service
  - php7.4-fpm.service
```

**Comment by kellyjonbrazil** [comment]
Hi @chriscroome - looks like it shouldn't be too hard to implement. Thanks for the suggestion!

**Comment by chriscroome** [comment]
The documentation for the variables names [from needrestart](https://github.com/liske/needrestart/blob/master/README.batch.md):

> Needrestart can be run in batch mode:
>
>```
> # needrestart -b
> NEEDRESTART-VER: 2.1
> NEEDRESTART-KCUR: 3.19.3-tl1+
> NEEDRESTART-KEXP: 3.19.3-tl1+
> NEEDRESTART-KSTA: 1
> NEEDRESTART-SVC: systemd-journald.service
> NEEDRESTART-SVC: systemd-machined.service
> NEEDRESTART-CONT: LXC web1
> NEEDRESTART-SESS: metabase @ user manager service
> NEEDRESTART-SESS: root @ session #28017
>```
>
> The kernel status (`NEEDRESTART-KSTA`) value has the following meaning:
>
> * 0: unknown or failed to detect
> * 1: no pending upgrade
> * 2: ABI compatible upgrade pending
> * 3: version upgrade pending


The documentation for the variables names [from apt-dater-host](https://github.com/DE-IBH/apt-dater-host/blob/master/doc/ADP-0.8):

> There should be `NEEDRESTART` line indicating the presence and the version of the needrestart(1) script:
>
>```
>    NEEDRESTART-VER: ${Version}
>```
>
> needrestart(1) is called in batch mode printing informations about services requiring restarts and outdated running kernels. The definition of the lines prefixed with `NEEDRESTART-` are defined by the needrestart package. The following lines are currently known:
>
>```
>    NEEDRESTART-KCUR: ${running kernel version}
>    NEEDRESTART-KEXP: ${expected kernel version}
>    NEEDRESTART-KSTA: ${kernel status}
>    NEEDRESTART-SVC: ${service}
>```

There is also a `PID` variable:

```bash
needrestart -b
NEEDRESTART-VER: 3.6
NEEDRESTART-PID: at-spi-bus-laun=2031
NEEDRESTART-PID: at-spi2-registr=2073
NEEDRESTART-PID: dbus-daemon=1754,2037
```

My suggestion is that with as soon as more than one `NEEDRESTART-WHATEVER` is found a list is needed and when not running in raw mode the variables returned might be best like this (with WHATEVER made lower case and changed from things like `CONT` to `container` and `SESS` to `session` &mdash; where we know what the human readable version is):

```yaml
version: "3.5"
running_kernel_version: "5.10.0-19-amd64"
expected_kernel_version: "5.10.0-20-amd64"
kernel_status: 3
kernel_status_description: "version upgrade pending" # see above for the list of the descriptions
service:
  - "exim4.service"
  - "php7.4-fpm.service"
pid:
  - "at-spi-bus-laun=2031"
  - "at-spi2-registr=2073"
  - "dbus-daemon=1754,2037"
container: "LXC web1"
session:
  - "metabase @ user manager service"
  - "root @ session #28017" # note this string has a # in it so it must be quoted
```

**Comment by chriscroome** [comment]
@anarcat has also been looking for [needrestart batch mode documentation](https://github.com/liske/needrestart/issues/230).

FWIW this is how I'm currently using Ansible to use `needrestart -b` output to [restart services](https://git.coop/webarch/upgrade/-/blob/d18f5293354d6b1deac1a8bc0a2a3bf516bc14da/tasks/restart.yml) and to [reboot](https://git.coop/webarch/upgrade/-/blob/d18f5293354d6b1deac1a8bc0a2a3bf516bc14da/tasks/reboot.yml).

**Comment by chriscroome** [comment]
On one machine I currently have this output (exit code `0`):

```yaml
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 5.10.0-19-amd64
NEEDRESTART-KEXP: 5.10.0-20-amd64
NEEDRESTART-KSTA: 3
NEEDRESTART-UCSTA: 1
NEEDRESTART-UCCUR: 0x08108109
Use of uninitialized value $ucode_vars{"AVAIL"} in concatenation (.) or string at /usr/sbin/needrestart line 904.
NEEDRESTART-UCEXP: 
NEEDRESTART-SVC: exim4.service
NEEDRESTART-SVC: NetworkManager.service
NEEDRESTART-SVC: packagekit.service
```

I'd suggest either ignoring lines that don't start with `NEEDRESTART-` or perhaps outputting them to standard error?
