### ISSUE TITLE
Data missing when parsing Let's encrypt certbot ini files 

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#344]
[certbot](https://github.com/certbot/certbot) generates INI files with paths like `/etc/letsencrypt/renewal/example.org.conf` and content like this:

```ini
# renew_before_expiry = 30 days
version = 1.21.0
archive_dir = /etc/letsencrypt/archive/example.org
cert = /etc/letsencrypt/live/example.org/cert.pem
privkey = /etc/letsencrypt/live/example.org/privkey.pem
chain = /etc/letsencrypt/live/example.org/chain.pem
fullchain = /etc/letsencrypt/live/example.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = PkrrjRfryfuLvsg5oGiQ
authenticator = webroot
webroot_path = /var/www/html,
server = https://acme-v02.api.letsencrypt.org/directory
renew_hook = /etc/letsencrypt/renewal-hooks/deploy/certbot-restart-services
[[webroot_map]]
test.example.org = /var/www/html
```

As far as I can see these are valid INI files but JC only outputs the first section of the file:

```bash
cat /etc/letsencrypt/renewal/example.org.conf | jc --ini -py
```
```yaml
---
version: 1.21.0
archive_dir: /etc/letsencrypt/archive/example.org
cert: /etc/letsencrypt/live/example.org/cert.pem
privkey: /etc/letsencrypt/live/example.org/privkey.pem
chain: /etc/letsencrypt/live/example.org/chain.pem
fullchain: /etc/letsencrypt/live/example.org/fullchain.pem
```

Am I missing something or is this a bug or a feature?

**Comment by kellyjonbrazil** [comment]
Not sure if this is a python-specific thing, but I guess there is no "real" INI standard. Python doesn't think this is a valid INI file (more precisely a valid Config file) because it is missing the first section header. This is the exception I get when running it through the stock `configparser` library:
```
configparser.MissingSectionHeaderError: File contains no section headers.
```
The reason it takes the first values in `jc` is because I have modified the INI parser to create a fake section header if one doesn't exist, which essentially turns it into the `--kv` parser. (the `--kv` parser just points to the `--ini` parser)

A workaround for this might be to just add a fake section header to the file before parsing with `jc`?

**Comment by chriscroome** [comment]
Thanks for explaining why it works as it does.

I came across this issue when adding a line to the `[renewalparams]` section, if it is missing, using Ansible, I was hoping to check if it is already there first by slurping it and parsing it with JC, however it works fine without checking the file first, for example:

```yaml
- name: Ensure that renewal config file contains the renew_hook
  community.general.ini_file:
  path: "/etc/letsencrypt/renewal/{{ common_name }}.conf"
  section: renewalparams
  option: renew_hook
  value: "{{ path_to_script }}"
  mode: 0644
  backup: true
```

Looking at [the source](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/ini_file.py) of the [Ansible community.general.ini_file module](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/ini_file.py) it appears to be doing what you have suggested, [adding a fake section](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/ini_file.py#L232)?

Is adding a work around like this something that you might consider for the JC parser?

**Comment by kellyjonbrazil** [comment]
Yep, I'll look into that. Might have to separate the INI and KV parsers to make that happen, but that shouldn't be an issue. I'll take a look at how they did it in Ansible.

**Comment by chriscroome** [comment]
Thanks @kellyjonbrazil I think the `--ini` parser is one of the most important ones that `jc` provides since key parts of so many stacks use this format (for example MariaDB/MySQL, PHP, Systemd etc.) and when combined with the [Ansible community.general.ini_file module](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/ini_file.py) really efficient and flexible roles can be written without the need to template the config files -- you can read the variables using `jc` and then only update variables that need changing using `community.general.ini_file`.

**Comment by kellyjonbrazil** [comment]
I split up the `kv` and `ini` parsers and added a fake top-level section if it is missing for the `ini` parser in `dev` (called `_top_level_section_`):
https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/ini.py
https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/kv.py
```
$ echo '# renew_before_expiry = 30 days
version = 1.21.0
archive_dir = /etc/letsencrypt/archive/example.org
cert = /etc/letsencrypt/live/example.org/cert.pem
privkey = /etc/letsencrypt/live/example.org/privkey.pem
chain = /etc/letsencrypt/live/example.org/chain.pem
fullchain = /etc/letsencrypt/live/example.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = PkrrjRfryfuLvsg5oGiQ
authenticator = webroot
webroot_path = /var/www/html,
server = https://acme-v02.api.letsencrypt.org/directory
renew_hook = /etc/letsencrypt/renewal-hooks/deploy/certbot-restart-services
[[webroot_map]]
test.example.org = /var/www/html' | jc --ini -p
{
  "_top_level_section_": {
    "version": "1.21.0",
    "archive_dir": "/etc/letsencrypt/archive/example.org",
    "cert": "/etc/letsencrypt/live/example.org/cert.pem",
    "privkey": "/etc/letsencrypt/live/example.org/privkey.pem",
    "chain": "/etc/letsencrypt/live/example.org/chain.pem",
    "fullchain": "/etc/letsencrypt/live/example.org/fullchain.pem"
  },
  "renewalparams": {
    "account": "PkrrjRfryfuLvsg5oGiQ",
    "authenticator": "webroot",
    "webroot_path": "/var/www/html,",
    "server": "https://acme-v02.api.letsencrypt.org/directory",
    "renew_hook": "/etc/letsencrypt/renewal-hooks/deploy/certbot-restart-services"
  },
  "[webroot_map": {
    "test.example.org": "/var/www/html"
  }
}
```
Does that work? I tried to use a top-level name that made sense, but probably would not be found in any other INI files. I'm open to suggestions.

**Comment by chriscroome** [comment]
Thanks for your quick work on this :-)

I'd suggest omitting the `_top_level_section_` in the output so, as YAML, it would look like this:

```yaml
version: 1.21.0
archive_dir: /etc/letsencrypt/archive/example.org
cert: /etc/letsencrypt/live/example.org/cert.pem
privkey: /etc/letsencrypt/live/example.org/privkey.pem
chain: /etc/letsencrypt/live/example.org/chain.pem
fullchain: /etc/letsencrypt/live/example.org/fullchain.pem
renewalparams:
  account: PkrrjRfryfuLvsg5oGiQ
  authenticator: webroot
  webroot_path: /var/www/html,
  server: https://acme-v02.api.letsencrypt.org/directory
  renew_hook: /etc/letsencrypt/renewal-hooks/deploy/certbot-restart-services
'[webroot_map':
  test.example.org: /var/www/html
```

Simply because this is an more accurate representation of the input.

I'd also suggest doing something like generating a pseudo-random top-level name for internal processing use that is based on the input, for example a sha256 sum of the input plus something else, like a `jc-` prefix or whatever, just in case someone has a `.ini` file with a `[_top_level_section_]` already.

**Comment by kellyjonbrazil** [comment]
Ah yes - that makes sense. Also, if I don't include the `_top_level_section` key in the result then the key doesn't need to be easily human-readable, so it can be more guaranteed to be unique.

I could also do something like generate a random header and check the string to see if that header exists. If so, generate a new one and try again until a unique one is found. With a long enough hash it shouldn't take more than one or two tries.

**Comment by chriscroome** [comment]
Sounds great :-)

**Comment by kellyjonbrazil** [comment]
Cool, I updated the ini parser in `dev` to the new logic. Let me know how it goes!

**Comment by chriscroome** [comment]
I've just tested it and it's prefect!

**Comment by kellyjonbrazil** [comment]
I wonder if I should also fix the `[DEFAULT]` section handling. I can fix that by temporarily renaming it just like the top-level attributes. Doesn’t seem like something a `jc` parser should be doing. (Seems like too much magic)

**Comment by chriscroome** [comment]
That sounds like a good idea, I must admit I didn't really understand the documentation for the `[DEFAULT]` section when I read it last night... :roll_eyes:

**Comment by kellyjonbrazil** [comment]
Yeah it’s behavior inherited from the python configparser library. I think it’s a convenience feature for setting default values in subsequent sections but I don’t think it’s relevant to an INI parser. I’ll figure out how to disable it or use the top-level trick to get rid of it. Thanks for your help on this!

**Comment by chriscroome** [comment]
One other issue, that is perhaps not an issue that can be addressed or should be on another thread, is duplicates, for example as far as I can see a `/etc/systemd/network/eth0.network` file could contain:

```ini
[Match]
Name=eth0
[Network]
Address=192.168.1.20/24
Gateway=192.168.1.1
DNS=1.1.1.1
DNS=8.8.8.8
```

This example is based on my reading of [the Debian wiki](https://wiki.debian.org/SystemdNetworkd) and the [Debian systemd.network man page](https://manpages.debian.org/bullseye-backports/systemd/systemd.network.5.en.html).

Currently this results in:

```yml
---
Match:
  Name: eth0
Network:
  Address: 192.168.1.20/24
  Gateway: 192.168.1.1
  DNS: 8.8.8.8
```
I guess ideally it would result in something like this perhaps?

```yml
---
Match:
  Name: eth0
Network:
  Address: 192.168.1.20/24
  Gateway: 192.168.1.1
  DNS:
    - 1.1.1.1
    - 8.8.8.8
```

With duplicated entries being transformed into lists? :man_shrugging:

**Comment by kellyjonbrazil** [comment]
Yeah I’ve just documented that the last value is used if there are duplicates. It looks like it may be possible to turn duplicates into a list. I think I’d implement that with a separate `—ini-dup` parser or something.

**Comment by kellyjonbrazil** [comment]
Ok, I just removed the special `[DEFAULT]` section handling behavior, so the INI parser should be pretty solid now.

**Comment by chriscroome** [comment]
Nice one!

A separate `--ini-dup` would be great for systemd files and I expect for other config files and outputs, for example `needrestart -b` (however `jc` doing a little more processing for that output would be better, see #339).

**Comment by kellyjonbrazil** [comment]
I created a new `--ini-dup` parser that preserves duplicate values. With this parser all values are lists. I was thinking of making them strings if they are single values and lists if they are multiples, but that makes the schema a bit more difficult to reason about so maybe this is a good way forward.

https://github.com/kellyjonbrazil/jc/blob/dev/jc/parsers/ini_dup.py
```
% echo '
quote> foo = fiz
bar = buz

[section1]
fruit = apple
color = blue
color = red

[section2]
fruit = pear
fruit = peach
color = green' | jc --ini-dup -p
{
  "foo": [
    "fiz"
  ],
  "bar": [
    "buz"
  ],
  "section1": {
    "fruit": [
      "apple"
    ],
    "color": [
      "blue",
      "red"
    ]
  },
  "section2": {
    "fruit": [
      "pear",
      "peach"
    ],
    "color": [
      "green"
    ]
  }
}
```

**Comment by chriscroome** [comment]
Good idea, I'll have a play with it and let you know how I get on.

**Comment by chriscroome** [comment]
Given a systemd unit file like `/etc/systemd/network/eth0.network` containing:

```ini
[Match]
Name=eth0
Type=ether
[Network]
Address=192.168.0.2/24
Address=192.168.0.3/24
Gateway=192.168.0.1
```

The `ini-dup` filter returns (as YAML):

```yaml
---
Match:
  Name:
  - eth0
  Type:
  - ether
Network:
  Address:
  - 192.168.0.2/24
  - 192.168.0.3/24
  Gateway:
  - 192.168.0.1
```

However I'd much rather it looked like this:

```yaml
---
Match:
  Name: eth0
  Type: ether
Network:
  Address:
  - 192.168.0.2/24
  - 192.168.0.3/24
  Gateway: 192.168.0.1
```

And I've spend a few hours trying to work out how I could generically transform the first YAML example above into to the second using Ansible / JMESPath but I'm not getting anywhere fast...
