### ISSUE TITLE
What about a jc Ansible module?

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#352]
I realise there is a [jc Ansible filter](https://docs.ansible.com/ansible/devel/collections/community/general/jc_filter.html), but it occurred to me that a `jc` module would potentially be easier and simpler to use and therefore be more useful.

If one were to be written perhaps it could have the ability to read files as well as the results of commands, however I guess it would be impossible to ensure that commands don't change anything, but only using commands that don't change things could be suggested as being best practice?

```yaml
- name: Register the SSHD config
  community.general.jc:
    path: /etc/ssh/sshd_config  # src: could be an alias for path
    type: auto                  # parser: could be alias for type, auto, the default, could use
  register: sshd_config         # the path / filename to determine the parser to use?

- name: Register the PHP 8.0 FPM configuration
  community.general.jc:
    src: /etc/php/8.0/fpm/php.ini
    parser: ini
  register: php80_fpm_configuration

- name: Register the UFW status
  community.general.jc:
    command: ufw status
    parser: ufw
  register: ufw_status

- name: Register the history for the foo User
  community.general.jc:
    command: history
  become: true
  become_user: foo
  register: foo_history
  
- name: Test rsync source to dest and register the results
  community.general.jc:
    command: rsync -i -a --dry-run source/ dest/
    parser: rsync               # parser: / type: could be optional if it can be automatically
  changed_when: false           # detected from the command being run?
  args:
    chdir: /foo/bar
  register: rsync_results
```

I know all the above examples can be implemented using `slurp`, `command` and `set_fact` so it isn't really needed but having a `community.general.jc` module would make life easier!

Just a thought...
