### ISSUE TITLE
Should the semver parser be more accepting?

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#357]
Some software doesn't strictly stick to the [Semantic Versioning](https://semver.org/) recommendations, for example `pip` has [MAJOR.MINOR and MAJOR.MINOR.PATCH](https://pypi.org/project/pip/#history), this means that some version work:

```bash
echo "22.3.1" | jc --semver -yp
```
```yaml
---
major: 22
minor: 3
patch: 1
prerelease:
build:
```

But others don't:

```bash
echo "22.3" | jc --semver -yp
```
```yaml
--- {}
```

Would it be worth considering supporting cases like this so the output would be:

```yaml
---
major: 22
minor: 3
patch: 
prerelease:
build:
```

@kellyjonbrazil do you have any thoughts about this?
