### ISSUE TITLE
ufw_appinfo doesn't work with ufw app info all?

### ISSUE THREAD

**Issue by chriscroome** [kellyjonbrazil/jc#394]
The [documentation](https://kellyjonbrazil.github.io/jc/docs/parsers/ufw_appinfo) contains:

> Supports individual apps via `ufw app info [application]` and all apps list via `ufw app info all`.

This works for one app:

```bash
ufw app info OpenSSH | jc --ufw-appinfo -yp
```
```yml
---
- profile: OpenSSH
  title: Secure shell server, an rshd replacement
  description: OpenSSH is a free implementation of the Secure Shell protocol.
  tcp_list:
  - 22
  normalized_tcp_list:
  - 22
```

However the `all` option doesn't appear to work?

```bash
ufw app info all | jc --ufw-appinfo -yp
jc:  Error - ufw-appinfo parser could not parse the input data.
             If this is the correct parser, try setting the locale to C (LC_ALL=C).
             For details use the -d or -dd option. Use "jc -h --ufw-appinfo" for help.
```
```bash
LC_ALL=C ufw app info all | jc --ufw-appinfo -yp
jc:  Error - ufw-appinfo parser could not parse the input data.
             If this is the correct parser, try setting the locale to C (LC_ALL=C).
             For details use the -d or -dd option. Use "jc -h --ufw-appinfo" for help.
```
```bash
export LANG=C && export LC_NUMERIC=C && ufw app info all | jc --ufw-appinfo -yp
jc:  Error - ufw-appinfo parser could not parse the input data.
             If this is the correct parser, try setting the locale to C (LC_ALL=C).
             For details use the -d or -dd option. Use "jc -h --ufw-appinfo" for help.
```

The command itself seems fine:

```bash
ufw app info all | head -n 18
Profile: AIM
Title: AIM Talk
Description: AIM talk protocol

Port:
  5190/tcp

--

Profile: Bonjour
Title: Bonjour
Description: Bonjour protocol

Ports:
  5353/udp
  5298

--
```

However I must admit that I prefer using the output the INI parser generates for this, for example:

```bash
cat /etc/ufw/applications.d/* | jc --ini -yp | tail -n 8
```
```yml
WWW Full:
  title: Web Server (HTTP,HTTPS)
  description: Web Server (HTTP,HTTPS)
  ports: 80,443/tcp
WWW Cache:
  title: Web Server (8080)
  description: Web Server (8080)
  ports: 8080/tcp
```

So I have no need for it to be fixed...
