### ISSUE TITLE
New parser request: ethtool

### ISSUE THREAD

**Issue by MrDrMcCoy** [kellyjonbrazil/jc#405]
`ethtool`, specifically the output for `ethtool ${interface_name}`, would be quite useful for myself and likely others as a parser option. I currently am able to parse this in Ansible with the following tasks:

```yaml
- name: Get more host interface metadata from ethtool
  shell: ethtool {{item}} | sed -E 's|^Settings for ||g;s|\t|  |g;s|^ +([a-zA-Z0-9 ]*:)|  \1|g'
  loop: "{{ansible_facts.interfaces}}"
  register: ethtool

- name: Update facts
  set_fact:
    # for whatever reason, we had to do this multiline string for the join instead of '\n'
    ethtool: >-
      {{
        ethtool.results
          | map(attribute='stdout')
          | reject('contains', 'No data available')
          | join('
      ')
          | from_yaml
      }}
```

While the above does work, it relies on somewhat brittle extended regex and may not be portable. An official parser in `jc` would be a massive improvement.
