### ISSUE TITLE
[bug]: jc parser cannot parse YAML field values that contain equal signs

### ISSUE THREAD

**Issue by lunrenyi** [kellyjonbrazil/jc#614]
- jc version: 1.25.3
- t.yml:
  ```yaml
  - Dec: 61
    Oct: "075"
    Hex: "0x3d"
    Ctrl: ""
    Acronym: =
    Description: =
    Description-zh: 等号
  ```
- Minimizing the case: `printf "%s\n" '- a: 1' '  b: =' | jc -p --yaml`
<img width="811" alt="image" src="https://github.com/user-attachments/assets/62c8ebf2-5a34-4b54-ada6-5db3d0287c01">
