### ISSUE TITLE
pkg: Cannot install package - 'jc v1.25.4'

### ISSUE THREAD

**Issue by kuanbase** [kellyjonbrazil/jc#623]
*Platform*: macOS15.0.1（24A348）

*Command*: x env use jc   

*Error*: 

```
- I|pkg: Running use pkg [name=jc] [version=v1.25.4]  ==>  use 

  S:
  - I|pkg: Step 1/2, Installing jc v1.25.4
  - I|pkg: |
      Downloading darwin/arm64 jc v1.25.4 dependency  ==>  miniconda
  - miniconda I|pkg: Trying download ==> 'miniconda v3.10.0+23.9.0-0'
  - miniconda I|pkg: |
      download miniconda=v3.10.0+23.9.0-0, thanks to the courtesy of https://mirrors.tuna.tsinghua.edu.cn
    more:
      url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-py310_23.9.0-0-MacOSX-arm64.sh
      ball: /Users/lamkuan/.x-cmd.root/local/data/pkg/download/miniconda/v3.10.0+23.9.0-0.darwin.arm64.0.sh
      name: miniconda
      version: v3.10.0+23.9.0-0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 79.6M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#=#=#                                                                          
  - miniconda E|pkg: File corrupted, except [3178aad8c75b30830e97d9a232433df1dfbe6cd34f55e0d7769cfaa17aa49e84] equal to [42000a3df40338672ac0fc14226a4a877202fe594289b7b71dec988188615fa6]
  - miniconda E|pkg: Failed to add darwin/arm64 'miniconda v3.10.0+23.9.0-0'
  - E|pkg: Failed to add darwin/arm64 'jc v1.25.4'
  - E|pkg: Cannot install package - 'jc v1.25.4'
```
